
<mujoco model="twist" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <!-- XACRO PARAMETERS -->
  


  <!-- rando stuff -->

  <xacro:property name="color_red" value="1.0 0.0 0.0"/>
  <xacro:property name="color_green" value="0.0 1.0 0.0"/>
  <xacro:property name="color_blue" value="0.0 0.0 1.0"/>
  <xacro:property name="color_dark_gray" value="0.25 0.25 0.25"/>
  <xacro:property name="color_gray" value="0.50 0.50 0.50"/>
  <xacro:property name="color_light_gray" value="0.75 0.75 0.75"/>

  <xacro:property name="pi" value="3.1415926"/>



  <!-- Body parameters -->

  <xacro:property name="motor_radius" value="0.03"/>
  <xacro:property name="motor_length" value="0.025"/>
  <xacro:property name="motor_mass" value="0.21"/>

  <xacro:property name="body_length" value="0.25"/>
  <xacro:property name="body_width" value="0.188"/>
  <xacro:property name="body_height" value="0.03"/>
  <xacro:property name="body_mass" value="0.67"/> <!--INERTIA PROB TOO HIGH, maybe make this a pointish mass-->

  <xacro:property name="body_to_hip_x" value="${body_length/2}"/>
  <xacro:property name="body_to_hip_y" value="${body_width/2}"/>
  <xacro:property name="body_to_hip_z" value="0.0"/>

  <xacro:property name="thigh_length" value="0.1"/>
  <xacro:property name="thigh_width" value="0.03"/>
  <xacro:property name="thigh_height" value="0.03"/>
  <xacro:property name="thigh_mass" value="0.0"/> <!-- but is it tho -->

  <xacro:property name="hip_limit_min" value="${-pi}"/>
  <xacro:property name="hip_limit_max" value="${pi}"/>
  <xacro:property name="hip_damping" value="0.351111"/> <!-- stolen from twist, update this -->

  <xacro:property name="shin_length" value="0.1"/>
  <xacro:property name="shin_width" value="0.03"/>
  <xacro:property name="shin_height" value="0.03"/>
  <xacro:property name="shin_mass" value="0.0"/> <!-- but is it tho -->

  <xacro:property name="knee_limit_min" value="${-pi}"/>
  <xacro:property name="knee_limit_max" value="${pi}"/>
  <xacro:property name="knee_damping" value="0.351111"/>
 
  <xacro:property name="toe_radius" value="0.0175"/> <!--toe properties also stolen from twist-->
  <xacro:property name="toe_mass" value="0.030"/>  <!--GTT: Grand Theft Toe-->
  


  

    <!-- XACRO MACROS -->
  
  <xacro:macro name="build_limb" params="limb_base_pos limb_index:=0">

    <xacro:property name="front_back_sign" value="${-1+2*(limb_index % 2)}"/>
    <xacro:property name="left_right_sign" value="${-1+2*(limb_index // 2)}"/>

    <!-- front_back_sign:=1 left_right_sign:=1" -->


    <body name="hip_${limb_index}" pos="${front_back_sign*body_to_hip_x} ${left_right_sign*body_to_hip_y} ${body_to_hip_z}" >
      <geom name="hip_motor_${limb_index}" size="${motor_radius} ${motor_length/2}" 
              pos="0 ${left_right_sign*0.03} 0"
              quat="0.707107 0.707107 0 0" type="cylinder" group="2"
              mass="${motor_mass}" rgba="0 0 ${1 - 0.33 * limb_index} 1" />

      <body name="thigh_${limb_index}" pos="0 0 0" quat=" 0.9659258 0 0.258819 0">
        <joint name="HIP${limb_index}" pos="0 0 0" axis="0 1 0" 
                range="${hip_limit_min} ${hip_limit_max}" damping="${hip_damping}"/>
        <geom name="thigh_${limb_index}" type="box" size="${thigh_width/2} ${thigh_height/2} ${thigh_length/2}"
                pos="0 0 ${-thigh_length/2}"
                mass="${thigh_mass}" rgba="0.8 0.8 0.8 1" />
        <geom name="knee_motor_${limb_index}" type="cylinder" size="${motor_radius} ${motor_length/2}" 
                pos="0 ${-left_right_sign*0.03} ${-thigh_length}"
                quat="0.707107 0.707107 0 0" group="2"
                mass="${motor_mass}" rgba="0 ${1 - 0.33 * limb_index} 0 1" />


        <body name="shin_${limb_index}" pos="0 0 ${-shin_length}"  quat="0.86603 0 -0.5 0">
          <joint name="KNEE${limb_index}" pos="0 0 0" axis="0 1 0" 
                range="${knee_limit_min} ${knee_limit_max}" damping="${knee_damping}"/>
          <geom name="shin_${limb_index}" type="box" size="${shin_width/2} ${shin_height/2} ${shin_length/2}"
                pos="0 0 ${-shin_length/2}"
                mass="${shin_mass}" rgba="0.8 0.8 0.8 1" />
          <geom name="toe_${limb_index}" type="cylinder" size="${shin_width/2} 0.0525" pos="0 0 ${-shin_length} " 
                quat="0.707107 0.707107 0 0"
                mass="${toe_mass}" rgba="0.5 0.5 0.5 1" contype='4' />

        </body>
      </body>
    </body>
	</xacro:macro>

  <compiler angle="radian" autolimits="true"/>
  
  <option timestep="0.001" gravity="0 0 -9.81"> 
	
  <!-- https://github.com/deepmind/mujoco/issues/941 -->
		<flag sensornoise="enable" energy="enable" contact="enable"/>
	</option>

  <default>
    <geom contype='4' conaffinity='0'/> <!-- condim='1' solref='0.005 1' solimp ="0.9 0.95 0.001 0.5 2"/>-->
  </default>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="512"/>
    <texture name="texplane" type="2d" builtin="checker" rgb1=".2 .3 .4" rgb2=".1 0.15 0.2" width="512" height="512" mark="cross" markrgb=".8 .8 .8"/>
    <texture name="texgeom" type="cube" builtin="flat" mark="cross" width="127" height="1278"
        rgb1="0.8 0.6 0.4" rgb2="0.8 0.6 0.4" markrgb="1 1 1" random="0.01"/>
    <material name="matplane" reflectance="0.3" texture="texplane" texrepeat="1 1" texuniform="true"/>
    <material name="matgeom" texture="texgeom" texuniform="true" rgba="0.8 0.6 .4 1"/>
  </asset>

  <worldbody>
    <geom name="floor" pos="0 0 0" size="0 0 .25" type="plane" material="matplane" contype='2' conaffinity='4'/>
    <light cutoff="100" diffuse="1 1 1" dir="-0 0 -1.3" directional="true" exponent="1" pos="0 0 1.3" specular=".1 .1 .1"/>
    <body name="body">
      <joint name="FLOATING" type="free"/>
      <geom name="kinegamiAndBoards" size="${(body_length/2) + 0.015} ${(body_width/2) + 0.015} ${body_height/2}" 
              pos="0 0 0" type="box"  
              group="1" mass="${body_mass}" rgba="0.88 0.88 0.88 1.0"/> 

      <xacro:build_limb limb_base_pos="${body_length/2} ${body_width/2} 0" limb_index="0" />
      <xacro:build_limb limb_base_pos="-${body_length/2} ${body_width/2} 0" limb_index="1" />
      <xacro:build_limb limb_base_pos="${body_length/2} -${body_width/2} 0" limb_index="2" />
      <xacro:build_limb limb_base_pos="-${body_length/2} -${body_width/2} 0" limb_index="3" />

      <site name="IMU"/>
    </body>
  </worldbody>


  <actuator>
    
		
	</actuator>

  <sensor>
    <!-- <accelerometer name="ACCEL" site="IMU"/>
    <gyro name="GYRO" site="IMU"/>
    <framequat name="QUAT" objtype="site" objname="IMU"/>
    <subtreecom name="COM" body="base"/> -->
  </sensor>
  
</mujoco>
