
<mujoco model="twist" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <!-- XACRO PARAMETERS -->
  <!-- Body parameters -->
  <xacro:property name="body_length" value="0.25"/>
  <xacro:property name="body_width" value="0.2"/>
  <xacro:property name="body_height" value="0.05"/>
  <xacro:property name="body_mass" value="1.900"/> <!--TODO UPDATE-->

  <xacro:property name="motor_length" value="0.03"/>
  <xacro:property name="motor_radius" value="0.060"/>
  <xacro:property name="motor_mass" value="0.1"/>
  
  <xacro:property name="upper_link_length" value="0.206"/>
  <xacro:property name="upper_link_width" value="0.05"/> <!--est. average-->
  <xacro:property name="upper_link_height" value="0.032"/>
  <xacro:property name="upper_link_mass" value="0.250"/> <!--TODO UPDATE-->

  <xacro:property name="lower_link_length" value="0.206"/><!--TODO UPDATE-->
  <xacro:property name="lower_link_radius" value="0.013"/>
  <xacro:property name="lower_link_mass" value="0.067"/> <!--TODO UPDATE-->

  <xacro:property name="toe_radius" value="0.0175"/> 
  <xacro:property name="toe_mass" value="0.030"/><!--TODO UPDATE-->

  <xacro:property name="pi" value="3.1415926"/>


  <!-- Body origins location descriptions, as calculated for front left leg -->
  <xacro:property name="limb_base_to_hip_joint_x" value="0.0"/>
  <xacro:property name="limb_base_to_hip_joint_y" value="0.0"/>
  <xacro:property name="limb_base_to_hip_joint_z" value="0.0"/>  

  <xacro:property name="hip_joint_to_upper_x" value="0.0"/>
  <!-- <xacro:property name="hip_joint_to_upper_y" value="${hip_joint_to_hip_module_y + (motor_length/2) + motor_length + knee_hip_gap + upper_link_height/2}"/> -->
  <xacro:property name="hip_joint_to_upper_y" value="0.0"/>
  <xacro:property name="hip_joint_to_upper_z" value="0.0"/>  

  <xacro:property name="upper_to_lower_x" value="0.0"/>
  <xacro:property name="upper_to_lower_y" value="0.0"/>
  <xacro:property name="upper_to_lower_z" value="${-upper_link_length}"/>  
  



  <xacro:property name="upper_to_upper_link_x" value="${-upper_link_length/2}"/>
  <xacro:property name="upper_to_upper_link_y" value="0.0"/>
  <xacro:property name="upper_to_upper_link_z" value="0.0"/>

  <xacro:property name="knee_hip_gap" value="0.022"/>


  <xacro:property name="hip_joint_to_hip_module_x" value="0.0"/>
  <xacro:property name="hip_joint_to_hip_module_y" value="-0.008375"/>
  <xacro:property name="hip_joint_to_hip_module_z" value="0.0"/>

  <xacro:property name="upper_to_knee_module_x" value="0"/>
  <xacro:property name="upper_to_knee_module_y" value="${(-upper_link_height/2) - (motor_length/2)}"/>
  <xacro:property name="upper_to_knee_module_z" value="${-upper_link_length}"/>

  <xacro:property name="lower_to_toe_x" value="0.0"/>
  <xacro:property name="lower_to_toe_y" value="0.0"/>
  <xacro:property name="lower_to_toe_z" value="-0.206"/>

  <xacro:property name="hip_limit_min" value="${-pi}"/>
  <xacro:property name="hip_limit_max" value="${pi}"/>
  <xacro:property name="hip_damping" value="0.351111"/>
  
  <xacro:property name="knee_limit_min" value="${-pi}"/>
  <xacro:property name="knee_limit_max" value="${pi}"/>
  <xacro:property name="knee_damping" value="0.351111"/>

  <xacro:property name="color_red" value="1.0 0.0 0.0"/>
  <xacro:property name="color_green" value="0.0 1.0 0.0"/>
  <xacro:property name="color_blue" value="0.0 0.0 1.0"/>
  <xacro:property name="color_dark_gray" value="0.25 0.25 0.25"/>
  <xacro:property name="color_gray" value="0.50 0.50 0.50"/>
  <xacro:property name="color_light_gray" value="0.75 0.75 0.75"/>

  

    <!-- XACRO MACROS -->
  
  <xacro:macro name="build_limb" params="limb_base_pos limb_index:=0">

    <xacro:property name="front_back_sign" value="${1-2*(limb_index % 2)}"/>
    <xacro:property name="left_right_sign" value="${1-2*(limb_index // 2)}"/>

    <!-- front_back_sign:=1 left_right_sign:=1" -->
    <body name="limb_base_${limb_index}" pos="${limb_base_pos}">
      <body name="hip_${limb_index}" pos="${front_back_sign*limb_base_to_hip_joint_x} ${left_right_sign*limb_base_to_hip_joint_y} ${limb_base_to_hip_joint_z}">
        
        <geom name="hip_module_${limb_index}" size="${motor_radius} ${motor_length/2}" 
              pos="${front_back_sign*hip_joint_to_hip_module_x} ${left_right_sign*hip_joint_to_hip_module_y} ${hip_joint_to_hip_module_z}"
              quat="0.707107 0.707107 0 0" type="cylinder" group="2"
              mass="${motor_mass}" rgba="0 0 ${1 - 0.33 * limb_index} 1" />


        <body name="upper_${limb_index}" pos="${front_back_sign*hip_joint_to_upper_x} ${left_right_sign*hip_joint_to_upper_y} ${hip_joint_to_upper_z}">
          <joint name="HIP${limb_index}" pos="0 0 0" axis="0 1 0" 
                range="${hip_limit_min} ${hip_limit_max}" damping="${hip_damping}"/>

          <geom name="knee_module_${limb_index}" type="cylinder" size="${motor_radius} ${motor_length/2}" 
                pos="${upper_to_knee_module_x} ${left_right_sign*upper_to_knee_module_y} ${upper_to_knee_module_z}"
                quat="0.707107 0.707107 0 0" group="2"
                mass="${motor_mass}" rgba="${color_green} 1" />
                
          <geom name="upper_link_${limb_index}" type="box" size="${upper_link_length/2} ${upper_link_width/2} ${upper_link_height/2} "
                pos="${upper_to_upper_link_x} ${left_right_sign*upper_to_upper_link_y} ${upper_to_upper_link_z}"
                mass="${upper_link_mass}" rgba="${color_blue} 1" />
          
          <body name="lower_${limb_index}" pos="${upper_to_lower_x} ${upper_to_lower_y} ${upper_to_lower_z}">
            <joint name="KNEE${limb_index}" pos="0 0 0" axis="0 1 0" 
                  range="${knee_limit_min} ${knee_limit_max}" damping="${knee_damping}"/>
            <geom name="lower_link_${limb_index}" type="cylinder" size="${lower_link_radius} ${lower_link_length/2}" 
                  pos="0 0 ${-lower_link_length/2}" group="2"
                  mass="${lower_link_mass}" rgba="${color_red} 1"/>
            <geom name="toe_${limb_index}" size="${toe_radius}" pos="0 0 ${lower_to_toe_z} " 
                  mass="${toe_mass}" rgba="0.1 0.1 0.1 1" contype='4' />
          </body>
        </body>
      </body>
    </body>
	</xacro:macro>

  <compiler angle="radian" autolimits="true"/>
  
  <option timestep="0.001" gravity="0 0 -9.81"> 
	
  <!-- https://github.com/deepmind/mujoco/issues/941 -->
		<flag sensornoise="enable" energy="enable" contact="enable"/>
	</option>

  <default>
    <geom contype='4' conaffinity='0'/> <!-- condim='1' solref='0.005 1' solimp ="0.9 0.95 0.001 0.5 2"/>-->
  </default>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="512"/>
    <texture name="texplane" type="2d" builtin="checker" rgb1=".2 .3 .4" rgb2=".1 0.15 0.2" width="512" height="512" mark="cross" markrgb=".8 .8 .8"/>
    <texture name="texgeom" type="cube" builtin="flat" mark="cross" width="127" height="1278"
        rgb1="0.8 0.6 0.4" rgb2="0.8 0.6 0.4" markrgb="1 1 1" random="0.01"/>
    <material name="matplane" reflectance="0.3" texture="texplane" texrepeat="1 1" texuniform="true"/>
    <material name="matgeom" texture="texgeom" texuniform="true" rgba="0.8 0.6 .4 1"/>
  </asset>

  <worldbody>
    <geom name="floor" pos="0 0 0" size="0 0 .25" type="plane" material="matplane" contype='2' conaffinity='4'/>
    <light cutoff="100" diffuse="1 1 1" dir="-0 0 -1.3" directional="true" exponent="1" pos="0 0 1.3" specular=".1 .1 .1"/>
    <body name="body">
      <joint name="FLOATING" type="free"/>
      <geom name="kinegamiAndBoards" size="${body_length/2} ${body_width/2} ${body_height/2}" 
              pos="0 0 0" type="box"  
              group="1" mass="${body_mass}" rgba="0.88 0.88 0.88 0.3"/> 
      <xacro:build_limb limb_base_pos="${body_length/2} ${body_width/2} 0" limb_index="0" />
      <xacro:build_limb limb_base_pos="-${body_length/2} ${body_width/2} 0" limb_index="1" />
      <xacro:build_limb limb_base_pos="${body_length/2} -${body_width/2} 0" limb_index="2" />
      <xacro:build_limb limb_base_pos="-${body_length/2} -${body_width/2} 0" limb_index="3" />

      <site name="IMU"/>
    </body>
  </worldbody>


  <actuator>
    
		
	</actuator>

  <sensor>
    <!-- <accelerometer name="ACCEL" site="IMU"/>
    <gyro name="GYRO" site="IMU"/>
    <framequat name="QUAT" objtype="site" objname="IMU"/>
    <subtreecom name="COM" body="base"/> -->
  </sensor>
  
</mujoco>
